package tech.ydb.exposed.dialect.integration.dao

import org.jetbrains.exposed.v1.core.Table
import org.jetbrains.exposed.v1.jdbc.insert
import org.jetbrains.exposed.v1.jdbc.selectAll
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import tech.ydb.exposed.dialect.YdbUlidTable
import tech.ydb.exposed.dialect.YdbUuidIdTable
import tech.ydb.exposed.dialect.integration.base.BaseYdbTest

class GeneratedIdsIT : BaseYdbTest() {

    object UuidItems : YdbUuidIdTable("generated_uuid_items") {
        val name = varchar("name", 255)
    }

    object UlidItems : YdbUlidTable("generated_ulid_items") {
        val name = varchar("name", 255)
    }

    override val tables: List<Table> = listOf(UuidItems, UlidItems)

    @Test
    fun `YdbUuidIdTable generates a native UUID on insert`() = tx {
        UuidItems.insert {
            it[name] = "uuid-backed"
        }

        val row = UuidItems.selectAll().single()
        // The id is auto-generated by clientDefault — we just verify the row landed and
        // the column is non-null. The actual id value is a fresh UUID.
        val id = row[UuidItems.id].value
        assertEquals(36, id.toString().length)
        assertEquals("uuid-backed", row[UuidItems.name])
    }

    @Test
    fun `YdbUlidTable generates a 26-char ULID on insert`() = tx {
        UlidItems.insert {
            it[name] = "ulid-backed"
        }

        val row = UlidItems.selectAll().single()
        assertEquals(26, row[UlidItems.id].value.length)
        assertEquals("ulid-backed", row[UlidItems.name])
    }
}
