CREATE TABLE IF NOT EXISTS `REALM_SMTP_CONFIG`
(
    `REALM_ID` Utf8 NOT NULL,
    `VALUE`    Utf8,
    `NAME`     Utf8 NOT NULL,

--     FOREIGN KEY (REALM_ID) REFERENCES REALM (ID),
    PRIMARY KEY (`REALM_ID`, `NAME`)
);
