CREATE TABLE IF NOT EXISTS `REALM_ENABLED_EVENT_TYPES`
(
    `REALM_ID` Utf8 NOT NULL,
    `VALUE`    Utf8 NOT NULL,

    INDEX      idx_realm_evt_types_realm GLOBAL ON (`REALM_ID`),
    PRIMARY KEY (`REALM_ID`, `VALUE`)
);
