CREATE TABLE IF NOT EXISTS `REQUIRED_ACTION_CONFIG`
(
    `REQUIRED_ACTION_ID` Utf8 NOT NULL,
    `VALUE`              Utf8,
    `NAME`               Utf8 NOT NULL,

    PRIMARY KEY (`REQUIRED_ACTION_ID`, `NAME`)
);
