CREATE TABLE IF NOT EXISTS RESOURCE_SERVER_SCOPE
(
    `ID`                 Utf8 NOT NULL,
    `NAME`               Utf8 NOT NULL,
    `ICON_URI`           Utf8,
    `RESOURCE_SERVER_ID` Utf8 NOT NULL,
    `DISPLAY_NAME`       Utf8,

    INDEX idx_res_srv_scope_res_srv GLOBAL ON (RESOURCE_SERVER_ID),
-- TODO: maybe create UNIQUE index `ON (NAME, RESOURCE_SERVER_ID)`
--     CONSTRAINT `UK_FRSRST700S9V50BU18WS5HA6` GLOBAL UNIQUE ON (NAME, RESOURCE_SERVER_ID),
--     FOREIGN KEY (RESOURCE_SERVER_ID) REFERENCES RESOURCE_SERVER (ID),
    PRIMARY KEY (ID)
);