CREATE TABLE IF NOT EXISTS CLIENT_SCOPE_ATTRIBUTES
(
    `SCOPE_ID` Utf8 NOT NULL,
    `VALUE`    Utf8,
    `NAME`     Utf8 NOT NULL,

    INDEX idx_clscope_attrs GLOBAL ON (SCOPE_ID),
--     FOREIGN KEY (SCOPE_ID) REFERENCES CLIENT_SCOPE (ID),
    PRIMARY KEY (SCOPE_ID, NAME)
);
