CREATE TABLE IF NOT EXISTS REDIRECT_URIS
(
    `CLIENT_ID` Utf8 NOT NULL,
    `VALUE`     Utf8 NOT NULL,

    INDEX idx_redir_uri_client GLOBAL ON (CLIENT_ID),
--     FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID),
    PRIMARY KEY (CLIENT_ID, VALUE)
);
