CREATE TABLE IF NOT EXISTS FED_USER_CONSENT_CL_SCOPE
(
    `USER_CONSENT_ID` Utf8 NOT NULL,
    `SCOPE_ID`        Utf8 NOT NULL,

    INDEX idx_fed_consent_cl_scope_consent GLOBAL ON (USER_CONSENT_ID),
    INDEX idx_fed_consent_cl_scope_scope GLOBAL ON (SCOPE_ID),
--     FOREIGN KEY (USER_CONSENT_ID) REFERENCES FED_USER_CONSENT (ID),
--     FOREIGN KEY (SCOPE_ID) REFERENCES CLIENT_SCOPE (ID),
    PRIMARY KEY (USER_CONSENT_ID, SCOPE_ID)
);