CREATE TABLE IF NOT EXISTS KEYCLOAK_GROUP
(
    `ID`           Utf8 NOT NULL,
    `NAME`         Utf8,
    `PARENT_GROUP` Utf8 NOT NULL,
    `REALM_ID`     Utf8,
    `TYPE`         Int32 NOT NULL DEFAULT 0,
    `DESCRIPTION`  Utf8,

--     CONSTRAINT `SIBLING_NAMES` GLOBAL UNIQUE ON (REALM_ID, PARENT_GROUP, NAME),
    PRIMARY KEY (ID)
);