CREATE TABLE IF NOT EXISTS RESOURCE_URIS
(
    `RESOURCE_ID` Utf8 NOT NULL,
    `VALUE`       Utf8 NOT NULL,

--     FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE_SERVER_RESOURCE (ID),
    PRIMARY KEY (RESOURCE_ID, VALUE)
);