CREATE TABLE IF NOT EXISTS USER_CONSENT_CLIENT_SCOPE
(
    `USER_CONSENT_ID` Utf8 NOT NULL,
    `SCOPE_ID`        Utf8 NOT NULL,

    INDEX idx_usconsent_clscope GLOBAL ON (USER_CONSENT_ID),
    INDEX idx_usconsent_scope_id GLOBAL ON (SCOPE_ID),
--     FOREIGN KEY (USER_CONSENT_ID) REFERENCES USER_CONSENT (ID),
--     FOREIGN KEY (SCOPE_ID) REFERENCES CLIENT_SCOPE (ID),
    PRIMARY KEY (USER_CONSENT_ID, SCOPE_ID)
);