CREATE TABLE IF NOT EXISTS RESOURCE_SERVER
(
    `ID`                    Utf8 NOT NULL,
    `ALLOW_RS_REMOTE_MGMT`  Bool NOT NULL DEFAULT false,
    `POLICY_ENFORCE_MODE`   Int16 NOT NULL,
    `DECISION_STRATEGY`     Int16 NOT NULL DEFAULT 1,

    PRIMARY KEY (ID)
);