CREATE TABLE IF NOT EXISTS COMPOSITE_ROLE
(
    `COMPOSITE`  Utf8 NOT NULL,
    `CHILD_ROLE` Utf8 NOT NULL,

    INDEX idx_composite GLOBAL ON (COMPOSITE),
    INDEX idx_composite_child GLOBAL ON (CHILD_ROLE),
    PRIMARY KEY (COMPOSITE, CHILD_ROLE)
);