CREATE TABLE IF NOT EXISTS IDP_MAPPER_CONFIG
(
    `IDP_MAPPER_ID` Utf8 NOT NULL,
    `VALUE`         Utf8,
    `NAME`          Utf8 NOT NULL,

--     FOREIGN KEY (IDP_MAPPER_ID) REFERENCES IDENTITY_PROVIDER_MAPPER (ID),
    PRIMARY KEY (IDP_MAPPER_ID, NAME)
);