CREATE TABLE IF NOT EXISTS POLICY_CONFIG
(
    `POLICY_ID` Utf8 NOT NULL,
    `NAME`      Utf8 NOT NULL,
    `VALUE`     Utf8,

--     FOREIGN KEY (POLICY_ID) REFERENCES RESOURCE_SERVER_POLICY (ID),
    PRIMARY KEY (POLICY_ID, NAME)
);