CREATE TABLE IF NOT EXISTS SCOPE_POLICY
(
    `SCOPE_ID`  Utf8 NOT NULL,
    `POLICY_ID` Utf8 NOT NULL,

    INDEX idx_scope_policy_policy GLOBAL ON (POLICY_ID),
    PRIMARY KEY (SCOPE_ID, POLICY_ID)
);
