CREATE TABLE IF NOT EXISTS USER_REQUIRED_ACTION
(
    `USER_ID`         Utf8 NOT NULL,
    `REQUIRED_ACTION` Utf8 NOT NULL DEFAULT " ",

    INDEX idx_user_reqactions GLOBAL ON (USER_ID),
--     FOREIGN KEY (USER_ID) REFERENCES USER_ENTITY (ID),
    PRIMARY KEY (REQUIRED_ACTION, USER_ID)
);