CREATE TABLE IF NOT EXISTS PROTOCOL_MAPPER_CONFIG
(
    `PROTOCOL_MAPPER_ID` Utf8 NOT NULL,
    `VALUE`              Utf8,
    `NAME`               Utf8 NOT NULL,

--     FOREIGN KEY (PROTOCOL_MAPPER_ID) REFERENCES PROTOCOL_MAPPER (ID),
    PRIMARY KEY (PROTOCOL_MAPPER_ID, NAME)
);