CREATE TABLE IF NOT EXISTS SCOPE_POLICY
(
    `SCOPE_ID`  Utf8 NOT NULL,
    `POLICY_ID` Utf8 NOT NULL,

    INDEX idx_scope_policy_policy GLOBAL ON (POLICY_ID),
--     FOREIGN KEY (SCOPE_ID) REFERENCES RESOURCE_SERVER_SCOPE (ID),
--     FOREIGN KEY (POLICY_ID) REFERENCES RESOURCE_SERVER_POLICY (ID),
    PRIMARY KEY (SCOPE_ID, POLICY_ID)
);
