CREATE TABLE IF NOT EXISTS SCOPE_MAPPING
(
    `CLIENT_ID` Utf8 NOT NULL,
    `ROLE_ID`   Utf8 NOT NULL,

    INDEX idx_scope_mapping_role GLOBAL ON (ROLE_ID),
--     FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID),
    PRIMARY KEY (CLIENT_ID, ROLE_ID)
);