CREATE TABLE IF NOT EXISTS CLIENT_SCOPE_ROLE_MAPPING
(
    `SCOPE_ID` Utf8 NOT NULL,
    `ROLE_ID`  Utf8 NOT NULL,

    INDEX idx_clscope_role GLOBAL ON (SCOPE_ID),
    INDEX idx_role_clscope GLOBAL ON (ROLE_ID),
--     FOREIGN KEY (SCOPE_ID) REFERENCES CLIENT_SCOPE (ID),
--     FOREIGN KEY (ROLE_ID) REFERENCES KEYCLOAK_ROLE (ID),
    PRIMARY KEY (SCOPE_ID, ROLE_ID)
);