CREATE TABLE IF NOT EXISTS ASSOCIATED_POLICY
(
    `POLICY_ID`            Utf8 NOT NULL,
    `ASSOCIATED_POLICY_ID` Utf8 NOT NULL,

    INDEX idx_assoc_pol_assoc_pol_id GLOBAL ON (ASSOCIATED_POLICY_ID),
--     FOREIGN KEY (POLICY_ID) REFERENCES RESOURCE_SERVER_POLICY (ID),
--     FOREIGN KEY (ASSOCIATED_POLICY_ID) REFERENCES RESOURCE_SERVER_POLICY (ID),
    PRIMARY KEY (POLICY_ID, ASSOCIATED_POLICY_ID)
);
