CREATE TABLE IF NOT EXISTS RESOURCE_SCOPE
(
    `RESOURCE_ID` Utf8 NOT NULL,
    `SCOPE_ID`    Utf8 NOT NULL,

    INDEX idx_res_scope_scope GLOBAL ON (SCOPE_ID),
    INDEX idx_res_scope_resource GLOBAL ON (RESOURCE_ID),
--     FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE_SERVER_RESOURCE (ID),
--     FOREIGN KEY (SCOPE_ID) REFERENCES RESOURCE_SERVER_SCOPE (ID),
    PRIMARY KEY (RESOURCE_ID, SCOPE_ID)
);