CREATE TABLE IF NOT EXISTS USER_FEDERATION_MAPPER_CONFIG
(
    `USER_FEDERATION_MAPPER_ID` Utf8 NOT NULL,
    `VALUE`                     Utf8,
    `NAME`                      Utf8 NOT NULL,

--     FOREIGN KEY (USER_FEDERATION_MAPPER_ID) REFERENCES USER_FEDERATION_MAPPER (ID),
    PRIMARY KEY (USER_FEDERATION_MAPPER_ID, NAME)
);