CREATE TABLE IF NOT EXISTS CLIENT_NODE_REGISTRATIONS
(
    `CLIENT_ID` Utf8 NOT NULL,
    `VALUE`     Int32,
    `NAME`      Utf8 NOT NULL,

--     FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID),
    PRIMARY KEY (CLIENT_ID, NAME)
);