CREATE TABLE IF NOT EXISTS REALM
(
    `ID`                           Utf8 NOT NULL,
    `ACCESS_CODE_LIFESPAN`         Int32,
    `USER_ACTION_LIFESPAN`         Int32,
    `ACCESS_TOKEN_LIFESPAN`        Int32,
    `ACCOUNT_THEME`                Utf8,
    `ADMIN_THEME`                  Utf8,
    `EMAIL_THEME`                  Utf8,
    `ENABLED`                      Bool  NOT NULL DEFAULT false,
    `EVENTS_ENABLED`               Bool  NOT NULL DEFAULT false,
    `EVENTS_EXPIRATION`            Int64,
    `LOGIN_THEME`                  Utf8,
    `NAME`                         Utf8,
    `NOT_BEFORE`                   Int32,
    `PASSWORD_POLICY`              Utf8,
    `REGISTRATION_ALLOWED`         Bool  NOT NULL DEFAULT false,
    `REMEMBER_ME`                  Bool  NOT NULL DEFAULT false,
    `RESET_PASSWORD_ALLOWED`       Bool  NOT NULL DEFAULT false,
    `SOCIAL`                       Bool  NOT NULL DEFAULT false,
    `SSL_REQUIRED`                 Utf8,
    `SSO_IDLE_TIMEOUT`             Int32,
    `SSO_MAX_LIFESPAN`             Int32,
    `UPDATE_PROFILE_ON_SOC_LOGIN`  Bool  NOT NULL DEFAULT false,
    `VERIFY_EMAIL`                 Bool  NOT NULL DEFAULT false,
    `MASTER_ADMIN_CLIENT`          Utf8,
    `LOGIN_LIFESPAN`               Int32,
    `INTERNATIONALIZATION_ENABLED` Bool  NOT NULL DEFAULT false,
    `DEFAULT_LOCALE`               Utf8,
    `REG_EMAIL_AS_USERNAME`        Bool  NOT NULL DEFAULT false,
    `ADMIN_EVENTS_ENABLED`         Bool  NOT NULL DEFAULT false,
    `ADMIN_EVENTS_DETAILS_ENABLED` Bool  NOT NULL DEFAULT false,
    `EDIT_USERNAME_ALLOWED`        Bool  NOT NULL DEFAULT false,
    `OTP_POLICY_COUNTER`           Int32 DEFAULT 0,
    `OTP_POLICY_WINDOW`            Int32 DEFAULT 1,
    `OTP_POLICY_PERIOD`            Int32 DEFAULT 30,
    `OTP_POLICY_DIGITS`            Int32 DEFAULT 6,
    `OTP_POLICY_ALG`               Utf8 DEFAULT 'HmacSHA1',
    `OTP_POLICY_TYPE`              Utf8 DEFAULT 'totp',
    `BROWSER_FLOW`                 Utf8,
    `REGISTRATION_FLOW`            Utf8,
    `DIRECT_GRANT_FLOW`            Utf8,
    `RESET_CREDENTIALS_FLOW`       Utf8,
    `CLIENT_AUTH_FLOW`             Utf8,
    `OFFLINE_SESSION_IDLE_TIMEOUT` Int32 NOT NULL DEFAULT 0,
    `REVOKE_REFRESH_TOKEN`         Bool  NOT NULL DEFAULT false,
    `ACCESS_TOKEN_LIFE_IMPLICIT`   Int32 NOT NULL DEFAULT 0,
    `LOGIN_WITH_EMAIL_ALLOWED`     Bool  NOT NULL DEFAULT true,
    `DUPLICATE_EMAILS_ALLOWED`     Bool  NOT NULL DEFAULT false,
    `DOCKER_AUTH_FLOW`             Utf8,
    `REFRESH_TOKEN_MAX_REUSE`      Int32 NOT NULL DEFAULT 0,
    `ALLOW_USER_MANAGED_ACCESS`    Bool  NOT NULL DEFAULT false,
    `SSO_MAX_LIFESPAN_REMEMBER_ME` Int32 NOT NULL DEFAULT 0,
    `SSO_IDLE_TIMEOUT_REMEMBER_ME` Int32 NOT NULL DEFAULT 0,
    `DEFAULT_ROLE`                 Utf8,

    INDEX                        realm_name_unique GLOBAL UNIQUE ON (NAME),
    INDEX                        idx_realm_master_adm_cli GLOBAL ON (MASTER_ADMIN_CLIENT),
    PRIMARY KEY (ID)
)
