CREATE TABLE IF NOT EXISTS `AUTHENTICATOR_CONFIG_ENTRY`
(
    `AUTHENTICATOR_ID` Utf8 NOT NULL,
    `VALUE`            Utf8,
    `NAME`             Utf8 NOT NULL,

    PRIMARY KEY (`AUTHENTICATOR_ID`, `NAME`)
);
