CREATE TABLE IF NOT EXISTS USER_CONSENT
(
    `ID`                      Utf8 NOT NULL,
    `CLIENT_ID`               Utf8,
    `USER_ID`                 Utf8 NOT NULL,
    `CREATED_DATE`            Int64,
    `LAST_UPDATED_DATE`       Int64,
    `CLIENT_STORAGE_PROVIDER` Utf8,
    `EXTERNAL_CLIENT_ID`      Utf8,

    INDEX idx_user_consent GLOBAL ON (USER_ID),
    INDEX idx_user_consent_client GLOBAL ON (CLIENT_ID),
--     CONSTRAINT `UK_LOCAL_CONSENT` GLOBAL UNIQUE ON (CLIENT_ID, USER_ID),
--     CONSTRAINT `UK_EXTERNAL_CONSENT` GLOBAL UNIQUE ON (CLIENT_STORAGE_PROVIDER, EXTERNAL_CLIENT_ID, USER_ID),
--     FOREIGN KEY (USER_ID) REFERENCES USER_ENTITY (ID),
--     FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID),
    PRIMARY KEY (ID)
);