CREATE TABLE IF NOT EXISTS USER_FEDERATION_MAPPER_CONFIG
(
    `USER_FEDERATION_MAPPER_ID` Utf8 NOT NULL,
    `VALUE`                     Utf8,
    `NAME`                      Utf8 NOT NULL,

    INDEX idx_usr_fed_map_cfg_mapper GLOBAL ON (USER_FEDERATION_MAPPER_ID),
    INDEX idx_usr_fed_map_cfg_name GLOBAL ON (NAME),
--     FOREIGN KEY (USER_FEDERATION_MAPPER_ID) REFERENCES USER_FEDERATION_MAPPER (ID),
    PRIMARY KEY (USER_FEDERATION_MAPPER_ID, NAME)
);