CREATE TABLE IF NOT EXISTS USER_FEDERATION_CONFIG
(
    `USER_FEDERATION_PROVIDER_ID` Utf8 NOT NULL,
    `VALUE`                       Utf8,
    `NAME`                        Utf8 NOT NULL,

    INDEX idx_user_fed_config_provider GLOBAL ON (USER_FEDERATION_PROVIDER_ID),
    INDEX idx_user_fed_config_name GLOBAL ON (NAME),
--     FOREIGN KEY (USER_FEDERATION_PROVIDER_ID) REFERENCES USER_FEDERATION_PROVIDER (ID),
    PRIMARY KEY (USER_FEDERATION_PROVIDER_ID, NAME)
);