CREATE TABLE IF NOT EXISTS KEYCLOAK_GROUP
(
    `ID`           Utf8 NOT NULL,
    `NAME`         Utf8,
    `PARENT_GROUP` Utf8 NOT NULL,
    `REALM_ID`     Utf8,
    `TYPE`         Int32 NOT NULL DEFAULT 0,
    `DESCRIPTION`  Utf8,

    INDEX idx_keycloak_group_parent GLOBAL ON (PARENT_GROUP),
    INDEX idx_keycloak_group_realm GLOBAL ON (REALM_ID),
--     CONSTRAINT `SIBLING_NAMES` GLOBAL UNIQUE ON (REALM_ID, PARENT_GROUP, NAME),
--     FOREIGN KEY (REALM_ID) REFERENCES REALM (ID),
--     FOREIGN KEY (PARENT_GROUP) REFERENCES KEYCLOAK_GROUP (ID),
    PRIMARY KEY (ID)
);