CREATE TABLE IF NOT EXISTS USER_FEDERATION_MAPPER
(
    `ID`                     Utf8 NOT NULL,
    `NAME`                   Utf8 NOT NULL,
    `FEDERATION_PROVIDER_ID` Utf8 NOT NULL,
    `FEDERATION_MAPPER_TYPE` Utf8 NOT NULL,
    `REALM_ID`               Utf8 NOT NULL,

    INDEX idx_usr_fed_map_fed_prv GLOBAL ON (FEDERATION_PROVIDER_ID),
    INDEX idx_usr_fed_map_realm GLOBAL ON (REALM_ID),
    INDEX idx_usr_fed_map_type GLOBAL ON (FEDERATION_MAPPER_TYPE),
--     FOREIGN KEY (FEDERATION_PROVIDER_ID) REFERENCES USER_FEDERATION_PROVIDER (ID),
--     FOREIGN KEY (REALM_ID) REFERENCES REALM (ID),
    PRIMARY KEY (ID)
);