CREATE TABLE IF NOT EXISTS CLIENT_AUTH_FLOW_BINDINGS
(
    `CLIENT_ID`    Utf8 NOT NULL,
    `FLOW_ID`      Utf8,
    `BINDING_NAME` Utf8 NOT NULL,

    INDEX idx_cl_auth_flow_client GLOBAL ON (CLIENT_ID),
    INDEX idx_cl_auth_flow_flow GLOBAL ON (FLOW_ID),
--     FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID),
--     FOREIGN KEY (FLOW_ID) REFERENCES AUTHENTICATION_FLOW (ID),
    PRIMARY KEY (CLIENT_ID, BINDING_NAME)
);