CREATE TABLE IF NOT EXISTS USER_GROUP_MEMBERSHIP
(
    `GROUP_ID`        Utf8 NOT NULL,
    `USER_ID`         Utf8 NOT NULL,
    `MEMBERSHIP_TYPE` Utf8 NOT NULL,

    INDEX idx_user_group_mapping GLOBAL ON (USER_ID),
    INDEX idx_user_group_group GLOBAL ON (GROUP_ID),
--     FOREIGN KEY (USER_ID) REFERENCES USER_ENTITY (ID),
--     FOREIGN KEY (GROUP_ID) REFERENCES KEYCLOAK_GROUP (ID),
    PRIMARY KEY (GROUP_ID, USER_ID)
);