CREATE TABLE IF NOT EXISTS GROUP_ROLE_MAPPING
(
    `ROLE_ID`  Utf8 NOT NULL,
    `GROUP_ID` Utf8 NOT NULL,

    INDEX idx_group_role_mapp_group GLOBAL ON (GROUP_ID),
    INDEX idx_group_role_mapp_role GLOBAL ON (ROLE_ID),
--     FOREIGN KEY (GROUP_ID) REFERENCES KEYCLOAK_GROUP (ID),
--     FOREIGN KEY (ROLE_ID) REFERENCES KEYCLOAK_ROLE (ID),
    PRIMARY KEY (ROLE_ID, GROUP_ID)
);