CREATE TABLE IF NOT EXISTS RESOURCE_POLICY
(
    `RESOURCE_ID` Utf8 NOT NULL,
    `POLICY_ID`   Utf8 NOT NULL,

    INDEX idx_res_policy_policy GLOBAL ON (POLICY_ID),
    INDEX idx_res_policy_resource GLOBAL ON (RESOURCE_ID),
--     FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE_SERVER_RESOURCE (ID),
--     FOREIGN KEY (POLICY_ID) REFERENCES RESOURCE_SERVER_POLICY (ID),
    PRIMARY KEY (RESOURCE_ID, POLICY_ID)
);