CREATE TABLE IF NOT EXISTS CLIENT_SCOPE_CLIENT
(
    `CLIENT_ID`     Utf8 NOT NULL,
    `SCOPE_ID`      Utf8 NOT NULL,
    `DEFAULT_SCOPE` Bool NOT NULL DEFAULT false,

    INDEX idx_clscope_cl GLOBAL ON (CLIENT_ID),
    INDEX idx_cl_clscope GLOBAL ON (SCOPE_ID),
    PRIMARY KEY (CLIENT_ID, SCOPE_ID)
);