CREATE TABLE IF NOT EXISTS ORG
(
    `ID`           Utf8 NOT NULL,
    `ENABLED`      Bool NOT NULL,
    `REALM_ID`     Utf8 NOT NULL,
    `GROUP_ID`     Utf8 NOT NULL,
    `NAME`         Utf8 NOT NULL,
    `DESCRIPTION`  Utf8,
    `ALIAS`        Utf8 NOT NULL,
    `REDIRECT_URL` Utf8,

--     CONSTRAINT `UK_ORG_GROUP` GLOBAL UNIQUE ON (GROUP_ID),
--     CONSTRAINT `UK_ORG_NAME` GLOBAL UNIQUE ON (REALM_ID, NAME),
--     CONSTRAINT `UK_ORG_ALIAS` GLOBAL UNIQUE ON (REALM_ID, ALIAS),
--     FOREIGN KEY (REALM_ID) REFERENCES REALM (ID),
    PRIMARY KEY (ID)
);