CREATE TABLE IF NOT EXISTS RESOURCE_SERVER_PERM_TICKET
(
    `ID`                 Utf8 NOT NULL,
    `OWNER`              Utf8 NOT NULL,
    `REQUESTER`          Utf8 NOT NULL,
    `CREATED_TIMESTAMP`  Int64 NOT NULL,
    `GRANTED_TIMESTAMP`  Int64,
    `RESOURCE_ID`        Utf8 NOT NULL,
    `SCOPE_ID`           Utf8,
    `RESOURCE_SERVER_ID` Utf8 NOT NULL,
    `POLICY_ID`          Utf8,

    INDEX idx_perm_ticket_requester GLOBAL ON (REQUESTER),
    INDEX idx_perm_ticket_owner GLOBAL ON (OWNER),
    INDEX idx_perm_ticket_resource GLOBAL ON (RESOURCE_ID),
    INDEX idx_perm_ticket_resource_server GLOBAL ON (RESOURCE_SERVER_ID),
    INDEX idx_perm_ticket_policy GLOBAL ON (POLICY_ID),
    INDEX idx_perm_ticket_scope GLOBAL ON (SCOPE_ID),
-- TODO: maybe create UNIQUE index `ON (OWNER, REQUESTER, RESOURCE_SERVER_ID, RESOURCE_ID, SCOPE_ID),`
--     CONSTRAINT `UK_FRSR6T700S9V50BU18WS5PMT` GLOBAL UNIQUE ON (OWNER, REQUESTER, RESOURCE_SERVER_ID, RESOURCE_ID, SCOPE_ID),
--     FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE_SERVER_RESOURCE (ID),
--     FOREIGN KEY (SCOPE_ID) REFERENCES RESOURCE_SERVER_SCOPE (ID),
--     FOREIGN KEY (RESOURCE_SERVER_ID) REFERENCES RESOURCE_SERVER (ID),
--     FOREIGN KEY (POLICY_ID) REFERENCES RESOURCE_SERVER_POLICY (ID),
    PRIMARY KEY (ID)
);