CREATE TABLE IF NOT EXISTS RESOURCE_URIS
(
    `RESOURCE_ID` Utf8 NOT NULL,
    `VALUE`       Utf8 NOT NULL,

    INDEX idx_resource_uris_resource GLOBAL ON (RESOURCE_ID),
    INDEX idx_resource_uris_value GLOBAL ON (VALUE),
--     FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE_SERVER_RESOURCE (ID),
    PRIMARY KEY (RESOURCE_ID, VALUE)
);