CREATE TABLE IF NOT EXISTS IDENTITY_PROVIDER_CONFIG
(
    `IDENTITY_PROVIDER_ID` Utf8 NOT NULL,
    `VALUE`                Utf8,
    `NAME`                 Utf8 NOT NULL,

    INDEX idx_idp_config_provider GLOBAL ON (IDENTITY_PROVIDER_ID),
--     FOREIGN KEY (IDENTITY_PROVIDER_ID) REFERENCES IDENTITY_PROVIDER (INTERNAL_ID),
    PRIMARY KEY (IDENTITY_PROVIDER_ID, NAME)
);