CREATE TABLE IF NOT EXISTS USER_ROLE_MAPPING
(
    `ROLE_ID` Utf8 NOT NULL,
    `USER_ID` Utf8 NOT NULL,

    INDEX idx_user_role_mapping GLOBAL ON (USER_ID),
--     FOREIGN KEY (USER_ID) REFERENCES USER_ENTITY (ID),
--     FOREIGN KEY (ROLE_ID) REFERENCES KEYCLOAK_ROLE (ID),
    PRIMARY KEY (ROLE_ID, USER_ID)
);