name: Kotlin Exposed YDB Dialect CI with Maven

on:
  push:
    branches:
      - main
    paths:
      - 'kotlin-exposed-dialect/**'
      - '.github/workflows/ci-exposed-ydb-dialect.yaml'
  pull_request:
    paths:
      - 'kotlin-exposed-dialect/**'
      - '.github/workflows/ci-exposed-ydb-dialect.yaml'

env:
  MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always

jobs:
  build:
    name: Kotlin Exposed YDB Dialect
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '17', '21' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Download dependencies
        working-directory: ./kotlin-exposed-dialect
        run: mvn $MAVEN_ARGS dependency:go-offline

      - name: Build & verify (unit + integration tests with testcontainers)
        working-directory: ./kotlin-exposed-dialect
        run: mvn $MAVEN_ARGS verify

      - name: Compile demo
        working-directory: ./kotlin-exposed-dialect/example
        run: mvn --batch-mode --update-snapshots compile
